// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIHHYSEnHFTnQo0rxx5KYrZaIdFyXak7Q',
    appId: '1:928884509564:web:314e41c6d9b109f4e2b2f9',
    messagingSenderId: '928884509564',
    projectId: 'grop-a3060',
    authDomain: 'grop-a3060.firebaseapp.com',
    databaseURL: 'https://grop-a3060-default-rtdb.firebaseio.com',
    storageBucket: 'grop-a3060.appspot.com',
    measurementId: 'G-XJ3SGENGND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_Jm94iK23-FX6j2_pZcl3fNiWilkwSA',
    appId: '1:928884509564:android:b422209c81cb0b11e2b2f9',
    messagingSenderId: '928884509564',
    projectId: 'grop-a3060',
    databaseURL: 'https://grop-a3060-default-rtdb.firebaseio.com',
    storageBucket: 'grop-a3060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOnmvgE72ajcs-CJKe2KUiz05wkHJ3zYc',
    appId: '1:928884509564:ios:9afa915275a6d4ede2b2f9',
    messagingSenderId: '928884509564',
    projectId: 'grop-a3060',
    databaseURL: 'https://grop-a3060-default-rtdb.firebaseio.com',
    storageBucket: 'grop-a3060.appspot.com',
    iosBundleId: 'com.example.grop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOnmvgE72ajcs-CJKe2KUiz05wkHJ3zYc',
    appId: '1:928884509564:ios:17330a3eac376100e2b2f9',
    messagingSenderId: '928884509564',
    projectId: 'grop-a3060',
    databaseURL: 'https://grop-a3060-default-rtdb.firebaseio.com',
    storageBucket: 'grop-a3060.appspot.com',
    iosBundleId: 'com.example.grop.RunnerTests',
  );
}
